config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts' => 'posts#index'
  get 'posts/new' => 'posts#new'
  get 'posts/:id' => 'posts#show', as: :post
  post 'posts' => 'posts#create'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'settings' => 'users#edit'
  get 'search' => 'users#index'
  get 'friends' => 'friendships#index'
  get 'messages' => 'conversations#index'
  post 'messages' => 'conversations#create'
  get 'messages/:id' => 'conversations#show', as: :conversation

  resources :friendships
  resources :users
  resources :posts do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :posts
	has_many :comments

	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	has_many :conversations, :foreign_key => :sender_id

	def self.search(query, n)
	  if n == 1
	  	where("first_name like ?", "%#{query}%")
	  else
	  	where("last_name like ?", "%#{query}%")
	  end
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
  	@users = User.all
  	@user = @users.find(params[:id])
  	@comment = Comment.all
  	@comment_new = Comment.new
  	@friendships = Friendship.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end


def index
	@friendships = Friendship.all
	if params[:first_name] == "" and params[:last_name] == ""
	    @users = ""
	elsif params[:first_name]
	    @users = User.search(params[:first_name], 1).search(params[:last_name], 2).order("created_at DESC")
	else
	    @users = User.all.order('created_at DESC')
	end
end



  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(user_params)
      redirect_to '/settings' 
    else
      render 'settings'
    end
  end


  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
- provide(:title, "Settings")
%h1 Update your profile
.form
  = form_for(@user) do |f|
    = f.label :name
    = f.text_field :first_name
    = f.label :surname
    = f.text_field :last_name
    = f.label :email
    = f.email_field :email
    = f.label :password, "New password"
    = f.password_field :password
    = f.label :password_confirmation, "Password confirmation"
    = f.password_field :password_confirmation
    = f.submit "Save changes", class: "btn-submit"

app/views/users/index.html.haml
.form
  %h1 Search for people
  = form_tag(users_path, :method => "get", id: "search-form") do
    = text_field_tag :first_name, params[:first_name], placeholder: "First name"
    = text_field_tag :last_name, params[:last_name], placeholder: "Last name"
    = submit_tag "Search", :name => nil, class: "btn-submit"
  - if params[:first_name] == "" and params[:last_name] == ""
  - elsif not params[:first_name] and not params[:last_name] and current_user.admin == false
  - else
    - @users.each do |user|
      .post
        %p.username= link_to (user.first_name + " " + user.last_name), user_path(user)
        -if current_user.admin == true
          %p.time= user.last_seen_at
          %p.joined= user.created_at
          %p.email= user.email
        - if session["user_id"] != user.id
          - begin
            - begin
              - @friendships.each do |friendship|
                - if friendship.friend == user.friends.find(session["user_id"]) and friendship.user == user
                  - if friendship.confirmed == 0
                    = link_to "Accept friendship", friendship, :method => "put"
                  - elsif friendship.confirmed == 1
                    %p= "Friends"
              - if @friendships.blank?
                = link_to "Add Friend", friendships_path(:friend_id => user), :method => :post
            - rescue
              - @friendships.each do |friendship|
                - if friendship.friend == current_user.friends.find(user.id) and friendship.user == current_user
                  - if friendship.confirmed == 0
                    = link_to "Delete request", friendship, :method => :delete
                  - elsif friendship.confirmed == 1
                    %p= "Friends"
          - rescue
            = link_to "Add Friend", friendships_path(:friend_id => user), :method => :post
%div

app/views/users/new.html.haml
.login
  .container
    .form
      %h1 Sign up
      = form_for(@user) do |f|
        = f.text_field :first_name, :placeholder => "First name"
        = f.text_field :last_name, :placeholder => "Last name"
        = f.email_field :email, :placeholder => "Email"
        = f.password_field :password, :placeholder => "Password"
        = f.password_field :password_confirmation, :placeholder => "Password Confirm"
        = f.submit "Create an account", class: "btn-submit"

app/views/users/show.html.haml
%h1
  = @user.first_name unless @user.blank?
  = @user.last_name unless @user.blank?
.panel
  - if session["user_id"] != @user.id
    - begin
      - begin
        - @friendships.each do |friendship|
          - if friendship.friend == @user.friends.find(session["user_id"]) and friendship.user == @user
            - if friendship.confirmed == 0
              = link_to "Accept friendship", friendship, :method => "put"
            - elsif friendship.confirmed == 1
              %p= "Friends"
        - if @friendships.blank?
          = link_to "Add Friend", friendships_path(:friend_id => @user), :method => :post
      - rescue
        - @friendships.each do |friendship|
          - if friendship.friend == current_user.friends.find(@user.id) and friendship.user == current_user
            - if friendship.confirmed == 0
              = link_to "Delete request", friendship, :method => :delete
            - elsif friendship.confirmed == 1
              %p= "Friends"
    - rescue
      = link_to "Add Friend", friendships_path(:friend_id => @user), :method => :post
  - else
    %p Your profile
.posts
  - @user.posts.each do |post|
    .post
      %p.author
        - unless post.user.blank?
          = link_to (post.user.first_name + " " + post.user.last_name), post.user
      %p.content= post.content
      %p.time= distance_of_time_in_words(post.created_at, Time.now) + " ago"
      - post.comments.each do |comment|
        .comments
          %p.author
            - unless comment.user.blank?
              = link_to (comment.user.first_name + " " + comment.user.last_name + " commented:"), comment.user
          %p.content= comment.content
          %p.time= distance_of_time_in_words(comment.created_at, Time.now) + " ago"
      = form_for [post, @comment_new] do |c|
        %p
          = c.label :comment, "New comment"
          %br/
          = c.text_area :content
        .actions= c.submit "Add comment"