config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts' => 'posts#index'
  get 'posts/new' => 'posts#new'
  get 'posts/:id' => 'posts#show', as: :post
  post 'posts' => 'posts#create'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'settings' => 'users#edit'
  get 'search' => 'users#index'
  get 'friends' => 'friendships#index'
  get 'messages' => 'conversations#index'
  post 'messages' => 'conversations#create'
  get 'messages/:id' => 'conversations#show', as: :conversation

  resources :friendships
  resources :users
  resources :posts do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new
  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
def create
  @friendship = current_user.friendships.build()
  @friendship.friend_id = params[:friend_id]
  @friendship.confirmed = 0
  if @friendship.save
    redirect_to (:back)
  else
    redirect_to (:back)
  end
end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
	friendship = Friendship.find_by_id(params[:id])
	friendship.confirmed = 1
	    if friendship.save
	      redirect_to (:back)
	    else
	      redirect_to (:back)
	    end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
def destroy
  @friendship = current_user.friendships.find(params[:id])
  @friendship.destroy
  redirect_to (:back)
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :confirmed, :create, :destroy)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.haml
= form_for(@friendship) do |f|
  - if @friendship.errors.any?
    #error_explanation
      %h2
        = pluralize(@friendship.errors.count, "error")
        prohibited this friendship from being saved:
      %ul
        - @friendship.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :friend_id
    %br/
    = f.number_field :friend_id
  .field
    = f.label :confirmed
    %br/
    = f.number_field :confirmed
  .field
    = f.label :create
    %br/
    = f.text_field :create
  .field
    = f.label :destroy
    %br/
    = f.text_field :destroy
  .actions
    = f.submit

app/views/friendships/edit.html.haml
%h1 Editing Friendship
= render 'form'
= link_to 'Show', @friendship
|
= link_to 'Back', friendships_path

app/views/friendships/index.html.haml
%p#notice= notice
%h1 Friendships
.form
  %h2 All friend requests recieved
  - current_user.inverse_friendships.each do |f|
    - if f.confirmed == 0
      .post
        %p.username= link_to (f.user.first_name + " " + f.user.last_name), user_path(f.friend)
        = link_to "Accept friendship", f, :method => "put"
  %br/
  %h2 All friend requests sent
  - current_user.friendships.each do |f|
    - if f.confirmed == 0
      .post
        %p.username= link_to (f.friend.first_name + " " + f.friend.last_name), user_path(f.friend)
        = link_to "Delete request", f, :method => :delete
  %br/
  = link_to 'Add friends', '/search'
  %h2 Your friends
  - list_of_friends.reverse_each do |f|
    .post
      %p.username= link_to (f.friend.first_name + " " + f.friend.last_name), user_path(f.friend)

app/views/friendships/new.html.haml
%h1 New Friendship
= render 'form'
= link_to 'Back', friendships_path

app/views/friendships/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @friendship.user_id
%p
  %strong Friend:
  = @friendship.friend_id
%p
  %strong Confirmed:
  = @friendship.confirmed
%p
  %strong Create:
  = @friendship.create
%p
  %strong Destroy:
  = @friendship.destroy
= link_to 'Edit', edit_friendship_path(@friendship)
|
= link_to 'Back', friendships_path