config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts' => 'posts#index'
  get 'posts/new' => 'posts#new'
  get 'posts/:id' => 'posts#show', as: :post
  post 'posts' => 'posts#create'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'settings' => 'users#edit'
  get 'search' => 'users#index'
  get 'friends' => 'friendships#index'
  get 'messages' => 'conversations#index'
  post 'messages' => 'conversations#create'
  get 'messages/:id' => 'conversations#show', as: :conversation

  resources :friendships
  resources :users
  resources :posts do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { order('created_at DESC') }

  belongs_to :user
  has_many :comments

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


    def index
      #FINDING FRIENDS POSTS
    	@list_of_friendships = current_user.friendships.all + current_user.inverse_friendships.all if current_user
    	@list_of_friendships.delete_if{|x| x.confirmed == 0} if current_user
    	@list_of_friendships.each{|x| x.friend = x.user if x.friend == current_user} if current_user
    	@post = Post.where(:user_id => current_user.id)
    	for x in @list_of_friendships
    		@post = @post + Post.where(:user_id => x.friend)
    	end
    	@post.sort!{|a,b| b.id.to_f <=> a.id.to_f } if not @post.blank? and not @list_of_friendships.blank?
      #LOAD MORE GENERATING
      if params[:id]
        @post = @post.reject{|x| x.id >= params[:id].to_i}.first(5)
      else
        @post = @post.first(5)
      end

    	@post_new = Post.new
    	@comment_new = Comment.new

      respond_to do |format|
        format.html
        format.js
        format.json { render json: @post }
      end
    end

  def create
    @post_new = current_user.posts.build(post_params)
    if @post_new.content == ""
      redirect_to '/'
    elsif @post_new.save
      redirect_to '/'
    else
      render '/'
    end
  end



  private
    def post_params
    	params.require(:post).permit(:content)
    end

before_action :require_user, only: [:index, :show]
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.haml
.post.post-record{ "data-id" => post.id }
  %p.author
    - unless post.user.blank?
      = link_to (post.user.first_name + " " + post.user.last_name), post.user
  %p.content= post.content
  %p.time= distance_of_time_in_words(post.created_at, Time.now) + " ago"
  - post.comments.each do |comment|
    .comments
      %p.author
        - unless comment.user.blank?
          = link_to (comment.user.first_name + " " + comment.user.last_name + ":"), comment.user
      %p.content= comment.content
      %p.time= distance_of_time_in_words(comment.created_at, Time.now) + " ago"
  = form_for [post, @comment_new] do |c|
    %p
      = c.label :comment, "New comment"
      %br/
      = c.text_area :content
    .actions= c.submit "Add comment"

app/views/posts/index.html.haml
- provide(:title, "RobBook")
.posts
  = form_for(@post_new) do |f|
    .field
      = f.label :post , " "
      %br/
      = f.text_area :content
    .actions
      = f.submit "Post" , class: "btn-submit"

  =render @post

- if not @post.blank?
  .load-more-container
    %h3.loading-gif{ "style" => "display:none;"}= "Loading"
    = link_to "Load More", posts_path, class: "load-more btn-submit"

app/views/posts/index.js.haml
$('.posts').append('#{escape_javascript(render(:partial => @post))}')

app/views/posts/new.html.haml
%h1 Posts#new
%p Find me in app/views/posts/new.html.erb