config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'posts' => 'posts#index'
  get 'posts/new' => 'posts#new'
  get 'posts/:id' => 'posts#show', as: :post
  post 'posts' => 'posts#create'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'settings' => 'users#edit'
  get 'search' => 'users#index'
  get 'friends' => 'friendships#index'
  get 'messages' => 'conversations#index'
  post 'messages' => 'conversations#create'
  get 'messages/:id' => 'conversations#show', as: :conversation

  resources :friendships
  resources :users
  resources :posts do
    resources :comments
  end
  resources :conversations do
    resources :messages
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => "User"

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { order('created_at DESC') }

  belongs_to :user
  has_many :comments

end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :posts
	has_many :comments

	has_many :friendships
	has_many :friends, :through => :friendships
	has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
	has_many :inverse_friends, :through => :inverse_friendships, :source => :user

	has_many :conversations, :foreign_key => :sender_id

	def self.search(query, n)
	  if n == 1
	  	where("first_name like ?", "%#{query}%")
	  else
	  	where("last_name like ?", "%#{query}%")
	  end
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 
  helper_method :list_of_friends 
  before_filter :set_last_seen_at



def current_user 
	begin
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	rescue
		session[:user_id] = nil 
		redirect_to '/' 
	end
end


def set_last_seen_at
  current_user.update_attribute(:last_seen_at, Time.now) if current_user
end

def list_of_friends
	@list_of_friendships = current_user.friendships.all + current_user.inverse_friendships.all if current_user
	@list_of_friendships.delete_if{|x| x.confirmed == 0} if current_user
	@list_of_friendships.each{|x| x.friend = x.user if x.friend == current_user} if current_user
	return @list_of_friendships if current_user
	return []
end

def require_user 
redirect_to '/login' unless current_user
end




end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment_new = current_user.comments.build(comment_params)
    @comment_new.post_id = params[:post_id]
    if @comment_new.content == ""
      redirect_to '/' 
    elsif @comment_new.save 
      redirect_to '/' 
    else 
      render '/' 
    end 
  end

  private 
    def comment_params 
    	params.require(:comment).permit(:content) 
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController


  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save!

    @path = conversation_path(@conversation)
    redirect_to :back
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


    def index
      #FINDING FRIENDS POSTS
    	@list_of_friendships = current_user.friendships.all + current_user.inverse_friendships.all if current_user
    	@list_of_friendships.delete_if{|x| x.confirmed == 0} if current_user
    	@list_of_friendships.each{|x| x.friend = x.user if x.friend == current_user} if current_user
    	@post = Post.where(:user_id => current_user.id)
    	for x in @list_of_friendships
    		@post = @post + Post.where(:user_id => x.friend)
    	end
    	@post.sort!{|a,b| b.id.to_f <=> a.id.to_f } if not @post.blank? and not @list_of_friendships.blank?
      #LOAD MORE GENERATING
      if params[:id]
        @post = @post.reject{|x| x.id >= params[:id].to_i}.first(5)
      else
        @post = @post.first(5)
      end

    	@post_new = Post.new
    	@comment_new = Comment.new

      respond_to do |format|
        format.html
        format.js
        format.json { render json: @post }
      end
    end

  def create
    @post_new = current_user.posts.build(post_params)
    if @post_new.content == ""
      redirect_to '/'
    elsif @post_new.save
      redirect_to '/'
    else
      render '/'
    end
  end



  private
    def post_params
    	params.require(:post).permit(:content)
    end

before_action :require_user, only: [:index, :show]
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
 def create
  @user = User.find_by_email(params[:session][:email])
  if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to '/'
  else
    redirect_to '/login'
  end 
end

  def destroy 
  session[:user_id] = nil 
  redirect_to '/' 
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
  	@users = User.all
  	@user = @users.find(params[:id])
  	@comment = Comment.all
  	@comment_new = Comment.new
  	@friendships = Friendship.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end


def index
	@friendships = Friendship.all
	if params[:first_name] == "" and params[:last_name] == ""
	    @users = ""
	elsif params[:first_name]
	    @users = User.search(params[:first_name], 1).search(params[:last_name], 2).order("created_at DESC")
	else
	    @users = User.all.order('created_at DESC')
	end
end



  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(user_params)
      redirect_to '/settings' 
    else
      render 'settings'
    end
  end


  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def conversation_interlocutor(conversation)
    conversation.recipient == current_user ? conversation.sender : conversation.recipient
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_friends_widget.html.haml
- if current_user
  .friends
    %p Friends
    - list_of_friends.reverse_each do |f|
      %div
        %p.username= link_to (f.friend.first_name + " " + f.friend.last_name), user_path(f.friend)
        %p.time= distance_of_time_in_words(f.friend.last_seen_at, Time.now) + " ago" if f.friend.last_seen_at

app/views/layouts/_links.html.haml
- if current_user
  %li= link_to "Home", '/'
  - if current_user.inverse_friendships.where(confirmed: 0).exists?
    %li.newFriendRequest= link_to "New Friends!", '/friends'
  - else
    %li= link_to "Friends", '/friends'
  %li= link_to "Messages", '/messages'
  %li= link_to "Search", '/users'
  %li= link_to "Settings", '/settings'
  %li= link_to "Log out", logout_path, method: "delete"
- else
  %li= link_to "Login", 'login'
  %li= link_to "Signup", 'signup'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Roboto:400,500,300", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.header.navbar-default{:role => "navigation"}
      .container-fluid
        = link_to root_path do
          #logo
          %h1#title RobBook
          - if current_user
            %p
              Hello #{current_user.first_name}!
          - else
            %p Welcome to RobBook!
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        #bs-example-navbar-collapse-1.collapse.navbar-collapse.pull-right
          %ul.nav.navbar-nav
            =render 'layouts/links'
    = yield
    =render 'layouts/friends_widget'